# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantlocation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 28, 17, 22, 42, 599495, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
